app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, request, flash, redirect, url_for


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    title = 'Home'
    return render_template('main/index.html', title=title)


@bp.route('/about-us')
def about():
    title = 'About Us'
    return render_template('main/about.html', title=title)


@bp.route('/services/construction')
def construction():
    title = 'Our Services > Construction'
    return render_template('main/construction.html', title=title)


@bp.route('/services/real-estate')
def real_estate():
    title = 'Our Services > Real Estate'
    return render_template('main/real-estate.html', title=title)


@bp.route('/projects')
def projects():
    title = 'Our Projects'
    return render_template('main/projects.html', title=title)


@bp.route('/services/procurement-and-supply')
def procurement():
    title = 'Sevices > Procurement & Supply'
    return render_template('main/procurement.html', title=title)


@bp.route('/services/procurement-and-supply/equipment/<name>')
def equipment(name):
    title = "Procurement & Supply > Engineering Components"
    return render_template('main/equipment-single.html', title=title)


@bp.route('/services/procurement-and-supply/material/<name>')
def material(name):
    title = "Procurement & Supply > Engineering Materials"
    return render_template('main/material-single.html', title=title)

app/templates/main/_partners.html
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
  integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
  integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

<section id="partners-s">
  <div class="row gx-0">
    <div class="col-xl-3">
      <div class="partners">our partners</div>
    </div>
    <div class="col-xl-9">
      <div class="partner-logo-div">
        <div class="my-slider text-center pt-3">
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/6.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/7.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/8.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/23.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/24.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/30.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/31.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/38.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/44.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/45.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/46.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/49.jpg') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
          <div>
            <div class="row justify-content-center">
              <img
                src="{{ url_for('static', filename='images/clients/50.png') }}"
                class="w-50"
                alt="Client logo"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- jQuery -->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"
  integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

<script>
  $(".my-slider").slick({
    centerMode: true,
    centerPadding: "75px",
    slidesToShow: 4,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 2400,
    arrows: false,
    dots: false,
    pauseOnHover: false,
    responsive: [
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 3,
        },
      },
      {
        breakpoint: 575,
        settings: {
          slidesToShow: 2,
        },
      },
      // You can unslick at a given breakpoint now by adding:
      // settings: "unslick"
      // instead of a settings object
    ],
  });
</script>

app/templates/main/_recent.html
<section id="projects-s">
  <div class="container">
    <div class="d-flex align-items-center">
      <div style="width: 150px"><p class="small-cap">Recent Projects</p></div>
      <div class="w-100 py-0"><hr class="mt-0 mb-2" /></div>
    </div>
    <div class="row">
      <div class="col-xl-3 p-3">
        <div class="canvas">
          <a href="{{ url_for('main.projects') }}">
            <div class="float">
              <img
                src="{{ url_for('static', filename='images/about.png') }}"
                class="w-100"
                alt=""
              />
              <div class="project-layer">
                <p class="small-cap mb-0" style="font-size: 14px">
                  sagamu, ogun state
                </p>
                <p class="mb-0 later-cap">
                  water-proofing factory complex
                </p>                
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

app/templates/main/_what.html
<section id="services-s">
  <div class="container">
    <div class="row gx-5 align-items-center">
      <div class="col-xl-6">
        <p class="small-cap mb-1">What we do</p>
        <p class="big-cap2 mb-3 text-white">
          SMART INNOVATION TO MASTER ANY ENGINEERING CHALLENGE
        </p>
        <p class="text2 text-white">
          We work with clients across all major infrastructure sectors and bring
          deep technical expertise to the world's most ambitious infrastructure
          projects
        </p>
      </div>
      <div class="col-xl-6">
        <div class="col-xl-9 ms-auto">
          <div class="row align-items-end text-white">
            <div class="col-xl-9 text-end">
              <p class="service-cap mb-1">
                <a href="{{ url_for('main.construction') }}"
                  >Construction Services</a
                >
              </p>
              <hr class="my-1" />
            </div>
            <div class="col-xl-3">
              <a href="{{ url_for('main.construction') }}">
                <img
                  src="{{ url_for('static', filename='images/about.png') }}"
                  class="service-thumb"
                  alt=""
                />
              </a>
            </div>
          </div>

          <div class="row align-items-end text-white mt-4">
            <div class="col-xl-9 text-end">
              <p class="service-cap mb-1">
                <a href="{{ url_for('main.real_estate') }}"
                  >Real Estate Development</a
                >
              </p>
              <hr class="my-1" />
            </div>
            <div class="col-xl-3">
              <a href="{{ url_for('main.real_estate') }}">
                <img
                  src="{{ url_for('static', filename='images/about.png') }}"
                  class="service-thumb"
                  alt=""
                />
              </a>
            </div>
          </div>

          <div class="row align-items-end text-white mt-4">
            <div class="col-xl-9 text-end">
              <p class="service-cap mb-1">
                <a href="{{ url_for('main.procurement') }}"
                  >Engineering Materials Supply</a
                >
              </p>
              <hr class="my-1" />
            </div>
            <div class="col-xl-3">
              <a href="{{ url_for('main.procurement') }}">
                <img
                  src="{{ url_for('static', filename='images/about.png') }}"
                  class="service-thumb"
                  alt=""
                />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/templates/main/about.html
{% extends 'base.html' %} {% block layout %}
<div id="about-hero" class="text-white">
  <div class="container">
    <div class="col-xl-7">
      <p class="big-cap2">
        about us<span class="material-icons mx-2"> arrow_forward_ios </span>who
        we are
      </p>
      <p class="intro-cap">
        Atkins brings together data, technology and people to help create a
        lived environment that works better for everyone.
      </p>
    </div>
  </div>
</div>
<section class="section-1">
  <div class="container">
    <div class="col-xl-10 mx-auto">
      <div class="d-flex align-items-center">
        <div style="width: 85px"><p class="small-cap">About us</p></div>
        <div class="w-100 py-0"><hr class="mt-0 mb-2" /></div>
      </div>
      <div class="row align-items-center gx-5">
        <div class="col-xl-6">
          <p class="intro-cap mb-0">
            As a market-leading design, engineering and project management
            consultancy we're transforming infrastructure delivery through
            competent bla bla bla.
          </p>
        </div>
        <div class="col-xl-6">
          <div class="p-2">
            <img
              src="{{ url_for('static', filename='images/about.png') }}"
              class="w-100"
              alt=""
            />
          </div>
        </div>
      </div>

      <div class="row align-items-center gx-5 mt-5">
        <div class="col-xl-6">
          <div class="p-2">
            <img
              src="{{ url_for('static', filename='images/about.png') }}"
              class="w-100"
              alt=""
            />
          </div>
        </div>
        <div class="col-xl-6">
          <p class="intro-cap mb-0">
            As a market-leading design, engineering and project management
            consultancy we're transforming infrastructure delivery through
            competent bla bla bla.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="mt-4 mb-5">
  <div class="container">
    <div class="col-xl-10 mx-auto">
      <div class="d-flex align-items-center mb-2">
        <div style="width: 130px"><p class="small-cap">our strengths</p></div>
        <div class="w-100 py-0"><hr class="mt-0 mb-2" /></div>
      </div>
      <div class="row g-3 pb-5">
        <div class="col-xl-4">
          <div class="rounded canvas">
            <img
              src="{{ url_for('static', filename='images/ab-test.jpg') }}"
              class="w-100"
              alt=""
            />
            <div class="slide-float">
              <div>people</div>
            </div>
          </div>
        </div>
        <div class="col-xl-4">
          <div class="rounded canvas">
            <a href="{{ url_for('main.projects') }}">
              <img
                src="{{ url_for('static', filename='images/ab-test.jpg') }}"
                class="w-100"
                alt=""
              />
            </a>
            <a href="{{ url_for('main.projects') }}">
              <div class="slide-float">
                <div>projects</div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-xl-4">
          <div class="rounded canvas">
            <a href="#partners-s">
              <img
                src="{{ url_for('static', filename='images/ab-test.jpg') }}"
                class="w-100"
                alt=""
              />
            </a>
            <a href="#partners-s">
              <div class="slide-float">
                <div>partners</div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include 'main/_what.html' %}
<section class="ceo">
  <div class="container">
    <div class="col-xl-9 mx-auto">
      <div class="row align-items-center">
        <div class="col-xl-4">
          <img
            src="{{ url_for('static', filename='images/adebayo.png') }}"
            class="w-100"
            alt="Picture of Jackland Engineering's CEO"
          />
        </div>
        <div class="col-xl-1"></div>
        <div class="col-xl-7">
          <div class="float">
            <span class="quote a">“</span>
            <p class="ceo-quote">
              Drinking garri is not a sign of poverty, but soaking it in water
              with the hope that it swells to a greater volume before drinking
              it, is definitely poverty.
            </p>
            <span class="quote b">”</span>
          </div>
          <div class="mt-5">
            <p class="ceo-name mb-0">Engr. Adeola Adefila</p>
            <p class="ceo-text">CEO, Jackland Engineering</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% include 'main/_partners.html' %} {% endblock %}

app/templates/main/construction.html
{% extends 'base.html' %} {% block layout %}
<div id="construction-hero">
  <div class="container">
    <div class="col-xl-7">
      <p class="big-cap2">
        Our Services<span class="material-icons mx-2"> arrow_forward_ios </span
        >Construction
      </p>
      <p class="big-cap">
        Atkins brings together data, technology and people to help create a
        lived environment that works better for everyone.
      </p>
    </div>
  </div>
</div>
<section class="section-1">
  <div class="container">
    <div class="row">
      <div class="col-xl-9">
        <p class="big-cap">
          As a market-leading design, engineering and project management
          consultancy we're transforming infrastructure delivery.
        </p>
        <p class="text1">
          We are thriving Nigerian construction company that executes projects
          in the areas of Civil, Water, Structures, and Municipal Engineering.
          Through partnerships and diversification, we are able to offer
          comprehensive services to our clients across the construction sector.
          Currently making a name for ourselves in the area of construction
          materials supply and installation, our aim is to grow to become one of
          the foremost engineering construction and supply companies in Nigeria.
        </p>
      </div>
      <div class="col-xl-3">
        <div class="col-xl-10 ms-auto">
          <div class="pix-nav d-none d-xl-block">
            <p>Construction</p>
            <ul class="target-links">
              <li><a href="#structural">structural works</a></li>
              <li><a href="#fabrication">fabrication works</a></li>
              <li><a href="#polysterene">polysterene works</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="structural" class="free">
  <div class="container">
    <div class="col-xl-9 mx-auto" style="position: relative; z-index: 100">
      <div class="row gx-0 c-border">        
        <div class="col-xl-6">
          <div class="p-center">
            <p class="narration-cap">
              Currently making a name for ourselves in the area of construction
              materials supply and installation, our aim is to grow to become
              one of the foremost 
            </p>
          </div>
        </div>
        <div class="col-xl-6">
          <img
            src="{{ url_for('static', filename='images/ab-test.jpg') }}"
            class="w-100"
            alt=""
          />
        </div>
      </div>
    </div>
  </div>
</section>

<section id="fabrication" class="free2 mt-5">
  <div class="container">
    <div class="col-xl-9 mx-auto" style="position: relative; z-index: 100">
      <div class="row gx-0 c-border">
        <div class="col-xl-6">
          <img
            src="{{ url_for('static', filename='images/ab-test.jpg') }}"
            class="w-100"
            alt=""
          />
        </div>
        <div class="col-xl-6">
          <div class="p-center">
            <p class="narration-cap">
              Currently making a name for ourselves in the area of construction
              materials supply and installation, our aim is to grow to become
              one of the foremost 
            </p>
          </div>
        </div>        
      </div>
    </div>
  </div>
</section>

<section id="polysterene" class="free mt-5">
  <div class="container">
    <div class="col-xl-9 mx-auto" style="position: relative; z-index: 100">
      <div class="row gx-0 c-border">        
        <div class="col-xl-6">
          <div class="p-center">
            <p class="narration-cap">
              Currently making a name for ourselves in the area of construction
              materials supply and installation, our aim is to grow to become
              one of the foremost 
            </p>
          </div>
        </div>
        <div class="col-xl-6">
          <img
            src="{{ url_for('static', filename='images/ab-test.jpg') }}"
            class="w-100"
            alt=""
          />
        </div>
      </div>
    </div>
  </div>
</section>

{% include 'main/_recent.html' %} {% endblock %}

app/templates/main/equipment-single.html
{% extends 'base.html' %} {% block layout %}
<div id="single-hero">
  <div class="container">
    <div class="col-xl-7">
      <p class="big-cap2">
        Our Services<span class="material-icons mx-2"> arrow_forward_ios </span
        >Engineering Materials Procurement & Supplyy
      </p>
      <p class="big-cap">
        Atkins brings together data, technology and people to help create a
        lived environment that works better for everyone.
      </p>
    </div>
  </div>
</div>

<section class="p5">
  <div class="container">
    <div class="col-xl-10 mx-auto">
      <div class="row g-5">
        <div class="col-xl-3">
          <div class="pix-nav2 d-none d-xl-block">
            <ul class="jump-links">              
              <li><a href="#props">Properties</a></li>
              <li><a href="#tech-sheet2">tech sheet</a></li>
            </ul>
          </div>
        </div>

        <div class="col-xl-9">
          <div id="images2">
            <div class="row gx-0">
              <div class="col-xl-8">
                <div
                  id="materialCarousel"
                  class="carousel slide"
                  data-mdb-ride="carousel"
                  data-mdb-touch="false"
                  data-mdb-interval="4000"
                >
                  <!-- Indicators -->
                  <div class="carousel-indicators">
                    <button
                      type="button"
                      data-mdb-target="#materialCarousel"
                      data-mdb-slide-to="0"
                      class="active"
                      aria-current="true"
                      aria-label="Slide 1"
                    ></button>
                    <button
                      type="button"
                      data-mdb-target="#materialCarousel"
                      data-mdb-slide-to="1"
                      aria-label="Slide 2"
                    ></button>
                    <button
                      type="button"
                      data-mdb-target="#materialCarousel"
                      data-mdb-slide-to="2"
                      aria-label="Slide 3"
                    ></button>
                    <button
                      type="button"
                      data-mdb-target="#materialCarousel"
                      data-mdb-slide-to="3"
                      aria-label="Slide 4"
                    ></button>
                  </div>

                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img
                        src="{{ url_for('static', filename='images/project-slides/1.png') }}"
                        class="d-block w-100"
                        alt="Banner with shopper images"
                      />
                    </div>

                    <div class="carousel-item">
                      <img
                        src="{{ url_for('static', filename='images/project-slides/2.png') }}"
                        class="d-block w-100"
                        alt="Banner with happy shoppers"
                      />
                    </div>

                    <div class="carousel-item">
                      <img
                        src="{{ url_for('static', filename='images/project-slides/3.png') }}"
                        class="d-block w-100"
                        alt="Banner with happy shopper"
                      />
                    </div>

                    <div class="carousel-item">
                      <img
                        src="{{ url_for('static', filename='images/project-slides/4.png') }}"
                        class="d-block w-100"
                        alt="Banner with happy shopper"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 d-none d-xl-block p-0">
                <div class="enclosure">
                  <h4>Acro Props</h4>
                  <a
                    type="button"
                    data-mdb-toggle="modal"
                    data-mdb-target="#contactModal"
                    class="btn btn-engr btn-block mt-2"
                  >
                    contact us</a
                  >
                </div>
              </div>
            </div>
          </div>
          <div id="props" class="pt-5">
            <p class="comp-cap mb-1">properties</p>
            <p class="comp-text mb-0">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque
              placeat magni hic saepe adipisci similique animi eius labore
              ducimus! Fugit ab aperiam quasi, minus, harum magnam facilis
              perspiciatis corporis soluta nisi iste laudantium cumque velit
              quos quidem qui similique. Architecto, mollitia officia! Dolor
              quisquam facilis reprehenderit nihil eum, beatae iure.
            </p>
          </div>
          <div id="tech-sheet2" class="pt-5">
            <p class="comp-cap">Tech sheet</p>
            <div class="d-none d-md-block">
              <iframe
                src="https://drive.google.com/file/d/1gBDj_ZQsU8K47xxzEeSZc1pD9maCe6Gg/preview"
                width="100%"
                height="600"
                allow="autoplay"
              ></iframe>
            </div>
            <div class="mt-5">
              <a
                href="https://drive.google.com/file/d/1gBDj_ZQsU8K47xxzEeSZc1pD9maCe6Gg/view?usp=sharing"
                download
                target="_blank"
                class="btn btn-jackland btn-block"
              >
                Download tech sheet
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %} 

{% block layout %}
<div id="home-hero">
  <div class="container h-100">
    <div class="row align-items-center gx-5 h-100">
      <div class="col-xl-6">
        <p class="big-cap mb-2">
          A WORLD-LEADING DESIGN, ENGINEERING AND PROJECT-MANAGEMENT CONSULTANCY
        </p>
      </div>
      <div class="col-xl-6">
        <img src="" alt="">
      </div>
    </div>
  </div>
</div>

<section id="about-s">
  <div class="container">
    <div class="row gx-5 align-items-center p-more">
      <div class="col-xl-6">
        <img
          src="{{ url_for('static', filename='images/about.png') }}"
          class="w-100"
          alt=""
        />
      </div>
      <div class="col-xl-6">
        <p class="small-cap mb-1">Who we are</p>
        <p class="big-cap mb-2">
          A WORLD-LEADING DESIGN, ENGINEERING AND PROJECT-MANAGEMENT CONSULTANCY
        </p>
        <p class="text1">
          Our lived environment is facing rapid change; to face these
          challenges, we are radically transforming the way infrastructure is
          designed, delivered and operated. Our aim is to help create a world
          that is diverse, sustainable, full of thriving communities and working
          better for all.
        </p>
      </div>
    </div>
  </div>
</section>
{% include 'main/_what.html' %} 
{% include 'main/_recent.html' %} 
{% include 'main/_partners.html' %} 
{% endblock %}

app/templates/main/procurement.html
{% extends 'base.html' %} {% block layout %}
<div id="material-hero">
  <div class="container">
    <div class="col-xl-7">
      <p class="big-cap2">
        Our Services<span class="material-icons mx-2"> arrow_forward_ios </span
        >Engineering Materials Procurement & Supplyy
      </p>
      <p class="big-cap">
        Atkins brings together data, technology and people to help create a
        lived environment that works better for everyone.
      </p>
    </div>
  </div>
</div>

<section class="p5">
  <div class="container">
    <div class="text-center">
      <ul class="nav nav-tabs switch" role="tablist">
        <li role="presentation">
          <a
            class="active"
            id="tab-1"
            data-mdb-toggle="tab"
            href="#tab-content-1"
            role="tab"
            aria-controls="tab-content-1"
            aria-selected="true"
            >Equipment</a
          >
        </li>
        <li class="mx-3">|</li>
        <li role="presentation">
          <a
            class=""
            id="tab-2"
            data-mdb-toggle="tab"
            href="#tab-content-2"
            role="tab"
            aria-controls="tab-content-2"
            aria-selected="false"
            >Materials</a
          >
        </li>
      </ul>
    </div>

    <!-- Tabs content -->
    <div class="tab-content mt-4">
      <div
        class="tab-pane fade show active"
        id="tab-content-1"
        role="tabpanel"
        aria-labelledby="tab-1"
      >
        <div class="row g-4 pt-2">
          <div class="col-xl-3">
            <div class="canvas">
              <a href="{{ url_for('main.equipment', name='Acro Props') }}">
                <div class="float">
                  <img
                    src="{{ url_for('static', filename='images/about.png') }}"
                    class="w-100"
                    alt=""
                  />
                  <div class="project-layer2">
                    <p class="small-cap mb-0" style="font-size: 14px">
                      sagamu, ogun state
                    </p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div
        class="tab-pane fade"
        id="tab-content-2"
        role="tabpanel"
        aria-labelledby="tab-2"
      >
        <div class="row g-4 pt-2">
          <div class="col-xl-3">
            <div class="canvas">
              <a href="{{ url_for('main.material', name='Fibre Mat') }}">
                <div class="float">
                  <img
                    src="{{ url_for('static', filename='images/about.png') }}"
                    class="w-100"
                    alt=""
                  />
                  <div class="project-layer2">
                    <p class="small-cap mb-0" style="font-size: 14px">
                      sagamu, ogun state
                    </p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Tabs content -->
  </div>
</section>
{% endblock %}